## Creacion de funcion XOR

Ejercicio en clase

In [1]:
def not_custom(x):
    parametros = [-1 , 1]
    return int(x * parametros[0] + parametros[1]>0)


In [2]:
test = 0
not_custom(test)

1

In [3]:
def or_custom(x1,x2):
    parametros = [1,1,0]
    
    return int(x1*parametros[0] + x2 * parametros[1] + parametros[2] >0) 

In [4]:
test1 = 0
test2 = 0
or_custom(test1,test2)

0

In [5]:
def and_custom(x1,x2):
    #otra opcion podria ser:
    # parametros = [1,1,-1]    
    # y compara que sea mayor a 0
    parametros = [1,1,0]
    
    return int(x1*parametros[0] + x2 * parametros[1] + parametros[2] >1) 

In [6]:
test1 = 1
test2 = 0
and_custom(test1,test2)

0

<img src="xor.png" width="500px">

In [7]:
def xor_custom(x1,x2):
    and1 = and_custom(x1,x2)
    or1 = or_custom(x1,x2)
    
    nand1 = not_custom(and1)
    
    salida = and_custom(nand1,or1)
    return salida

In [9]:
test1 = 0
test2 = 1
xor_custom(test1,test2)

1

# Parte 1
## XOR Vectorizado

In [12]:
import numpy as np

In [123]:
def vnot_1(x):
    b = np.ones(x.shape)
    b = np.vstack((x,b)).astype(int)
    a = np.array([[-1,1]])
    c = np.matmul(a,b)
    return c

In [137]:
def vnot(x):
    return (x == 0).astype(int)

In [125]:
test = np.array([1,0,1,0,0,0,0,1,1,1,])
print(vnot_1(test))
print(vnot(test))

[[0 1 0 1 1 1 1 0 0 0]]
[0 1 0 1 1 1 1 0 0 0]


In [126]:
def vand(x1, x2):
    return np.int_((x1 + x2)> 1)

In [127]:
test1= np.array([1,1,0,0])
test2= np.array([0,1,0,1])

vand(test1, test2)


array([0, 1, 0, 0])

In [128]:
def vor(x1,x2):
    return np.int_((x1 + x2)>= 1)
    

In [129]:
test1= np.array([1,1,0,0])
test2= np.array([0,1,0,1])

vor(test1, test2)


array([1, 1, 0, 1])

In [140]:
def vxor(x1,x2):
    and1 = vand(x1,x2)
    or1 = vor(x1,x2)
    
    nand1 = vnot(and1)
    salida = vand(nand1,or1)
    return salida

In [141]:
test1= np.array([1,1,0,0])
test2= np.array([0,1,0,1])

vxor(test1, test2)


array([1, 0, 0, 1])