## Practica 5
#### Forward propagation y representacion intermedia

Creacion de Fordward propagation de las graficas

In [1]:
import numpy as np

In [71]:
class ForwardProg:
    def __init__(self, w1, w2):    
        self.wl1 = w1

        # 1 elemento para cada neurona intermedia
        self.wl2 = w2

    def sigmoid(self,x):
        return 1/(1+np.exp(-x))
    
    def ite_propagation(self,x, add_sesgo= False):
        #print(x.shape)
        #print(self.wl1.shape)
        #print(self.wl1.T.shape)
        #print(np.matmul(x,self.wl1))
        hidden = self.sigmoid(np.matmul(x,self.wl1.T))
        #print(hidden.shape)
        if add_sesgo:
            largo = hidden.shape[0]
            sesgo = np.ones(largo).reshape(largo,1)
            #print(sesgo.shape)
            #print(hidden.shape)
            hidden = np.hstack((hidden,sesgo))
            #print(hidden.shape)
        #print(hidden.shape)
        #print(self.wl2.shape)
        sal = self.sigmoid(np.matmul(hidden,self.wl2.T))
        #print(sal.shape)
        return sal

<center><img src="diagrama1.png"/> </center>

In [73]:
x1 = np.array([
 [5, 10, 1],
 [1, 1, 1],
 [0, 1, 1],    
 [10, 5, 1],
])

w11 = np.array([
    [5, -2, -8],
    [7, -3, 1]
])

w12 = np.array([[7, 5, -6]])

red1  = ForwardProg(w11,w12)
red1.ite_propagation(x1,True)

array([[0.33617605],
       [0.27158134],
       [0.00447989],
       [0.99752738]])

<center><img src="diagrama2.png"/> </center>

In [74]:
x2 = np.array([
 [1, 1],
 [0, 0],
 [0, 1],    
 [1, 0],
 [2, 4],    
 [3, 9],
])

w21 = np.array([
    [8, 0.2],
    [0.4, 0.9],
    [0.3, 0.5]
])

w22 = np.array([[0.3, 0.5, 0.9]])

red2  = ForwardProg(w21,w22)
red2.ite_propagation(x2)

array([[0.78815037],
       [0.70056714],
       [0.74661477],
       [0.75329089],
       [0.83640392],
       [0.84499949]])

<img src="diagrama3.png"/>

In [76]:
x3 = np.array([
 [1, 1, 1],
 [0, 0, 1],
 [0, 1, 1],    
 [1, 0, 1],
 [2, 4, 1],    
 [3, 9, 1],
])

w31 = np.array([
    [20, 20, -10],
    [-20, -20, 30]
])

w32 = np.array([[20, 20, -30]])

red3  = ForwardProg(w31,w32)
red3.ite_propagation(x3)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [2]:
wc1 = np.array([
    [0.9, 0.8, 0.1],
    [0.3, 0.5, 0.6],
    [0.2, 0.4, 0.7]])

wc2 = np.array([0.3, 0.5, 0.9])

In [3]:
x = np.array([
    [1, 0, 1],
    [1, 2, 3],
    [4, 5, 6],
    [6, 7, 8],
])

In [6]:
H = np.matmul(x,wc1)
A = sigmoid(H)
h2 = np.matmul(A,wc2)
y_aprox = sigmoid(h2)
y_aprox

array([0.77387413, 0.83403412, 0.84538425, 0.84552612])